export const environment = {
  production: true,
  timeToHideSavedMessage: 3000,
  tokenWhitelistedDomains: [ /localhost:8080/ ],
  tokenBlacklistedRoutes: [/\/oauth\/token/],
  databaseHost: 'http://ss07.planejamento.es.gov.br/',
  baseAPIPath: 'api/',
  oauthAPI: 'oauth/',
  tokenResource: 'token',
  tokensRevoke: 'tokens/revoke',
  officeAPI: 'office/',
  PlanAPI: 'plan/',
  listPlansFunction: 'listplans/',
  workpackAPI: 'workpack/',
  listWorkpacksFunction: 'listworkpacks/',
  planStructureAPI: 'planstructure/',
  listPlanStructuresFunction: 'listplanstructures/',
  workpackModelAPI: 'workpackmodel/',
  propertyAPI: 'property/',
  propertyProfileAPI: 'propertyprofile/',
  listWorkpackModelsFunction: 'listworkpackmodels/',
  treeResource: 'tree/',
  defaultResource: 'default/',
  modelResource: 'model/',
  propertyTypesResource: 'listpropertytypes/',
  personAPI: 'person/',
  personLikeResource: 'like/',
  orgAPI: 'organization/',
  localityAPI: 'locality/',
  roleAPI: 'role/',
  relatedLocalityAPI: 'relatedlocality',
  byScopeIdResource: 'scope/',
  byActorIdResource: 'actor/',
};
